# Site settings
title: Grow
email: marlinf@datashaman.com
description: Planting schedule for South African fruit, vegetables and herbs.
baseurl: "/grow" # the subpath of your site, e.g. /blog/
url: "http://datashaman.github.io" # the base hostname & protocol for your site
google_api_key: AIzaSyBUE58hcq5yxNE_-tL-YCGPdfZ39mYgKTw

# Build settings
markdown: kramdown
exclude:
  - Gemfile*
  - Makefile
  - assets
  - bower.json
  - gulpfile
  - js/.module-cache
  - node_modules
  - package.json
