# Site settings
title: Grow
email: marlinf@datashaman.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/grow" # the subpath of your site, e.g. /blog/
url: "http://datashaman.github.io" # the base hostname & protocol for your site
twitter_username: data_shaman
github_username:  datashaman
google_api_key: AIzaSyBUE58hcq5yxNE_-tL-YCGPdfZ39mYgKTw

# Build settings
markdown: kramdown
exclude:
  - Gemfile*
  - Makefile
  - assets
  - bower.json
  - gulpfile
  - js/.module-cache
  - node_modules
  - package.json
